version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
  web_1:
    build: .
    command: bash -c "rm -f tmp/pids/server1.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -P tmp/pids/server1.pid"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka
    environment:
      - DB_DATABASE=app_1
      - APP_NAME=Integro
      - APP_ID=1

  web_2:
    build: .
    command: bash -c "rm -f tmp/pids/server2.pid && bundle exec rails s -p 3001 -b '0.0.0.0' -P tmp/pids/server2.pid"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
      - kafka
    environment:
      - DB_DATABASE=app_2
      - APP_NAME=Capsil
      - APP_ID=2

  web_3:
    build: .
    command: bash -c "rm -f tmp/pids/server3.pid && bundle exec rails s -p 3002 -b '0.0.0.0' -P tmp/pids/server3.pid"
    volumes:
      - .:/myapp
    ports:
      - "3002:3002"
    depends_on:
      - db
      - kafka
    environment:
      - DB_DATABASE=app_3
      - APP_NAME=Reporting Database
      - APP_ID=3
